[package]
name = "katastrophe"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "2.0.5"
once_cell = "1.19.0"
paste = "1.0.14"
